<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Python 入门 之 异常处理' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Python 入门 之 异常处理</center></div><div class='banquan'>原文出处:本文由博客园博主永亮提供。<br/>
原文连接:https://www.cnblogs.com/caiyongliang/p/11731978.html</div><br>
    <h1 id="python-入门-之-异常处理">Python 入门 之 异常处理</h1>
<h2 id="异常处理">1、异常处理</h2>
<h3 id="程序中的错误分为两种">（1）程序中的错误分为两种</h3>
<h5 id="语法错误">&lt;1&gt; 语法错误</h5>
<p>（这种错误，根本过不了Python解释器的语法检测，必须在程序执行前就改正）</p>
<pre><code><code># 语法错误示范
    print(111
    [1;2;3;4]</code></pre>
<h5 id="逻辑错误">&lt;2&gt; 逻辑错误</h5>
<pre><code><code># 逻辑错误示例
    lst = [1,2,3]
    lst[5]

    dic = {&quot;key&quot;:1}
    dic[&quot;name&quot;]

    1 + &quot;alex&quot;
    int(&quot;alex&quot;)

    name = &quot;alex&quot;
    def func():
        print(name)
        name = &quot;a&quot;
    func()</code></pre>
<h3 id="什么是异常">（2）什么是异常？</h3>
<h5 id="异常就是程序运行时发生错误的信号除去语法错误就是异常">异常就是程序运行时发生错误的信号，除去语法错误就是异常</h5>
<p>（异常就是在语法上是没有问题,但是运行时就报错的称为异常, 异常发生之后剩余代码将不会继续执行）</p>
<h3 id="异常种类">（3）异常种类：</h3>
<p>​ 在python中不同的异常可以用不同的类型（Python中统一了类与类型，类型即类）去标识，不同的类对象标识不同的异常，一个异常标识一种错误</p>
<h5 id="常见的异常">常见的异常：</h5>
<table>
<thead>
<tr class="header">
<th>异常类型</th>
<th>异常描述</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AttributeError</td>
<td>试图访问一个对象没有的属性,例如f.x 但是f没有属性x</td>
</tr>
<tr class="even">
<td>ImportError</td>
<td>无法引入模块或包；基本上是路径问题或名称错误</td>
</tr>
<tr class="odd">
<td>IndentationError</td>
<td>代码没有正确对齐</td>
</tr>
<tr class="even">
<td>IndexError</td>
<td>下标索引超出序列索引边界</td>
</tr>
<tr class="odd">
<td>KeyError</td>
<td>试图访问字典里不存在的键</td>
</tr>
<tr class="even">
<td>NameError</td>
<td>使用一个还未被赋予对象的变量</td>
</tr>
<tr class="odd">
<td>SyntaxError</td>
<td>Python遇到非法代码，代码不能编译</td>
</tr>
<tr class="even">
<td>TypeError</td>
<td>传入对象类型与要求的不符合</td>
</tr>
<tr class="odd">
<td>UnboundLocalError</td>
<td>试图访问一个还未被设置的局部变量，基本上是由于另有一个同名的全局变量</td>
</tr>
<tr class="even">
<td>ValueError</td>
<td>传入一个调用者不期望的值，即使值的类型是正确的</td>
</tr>
</tbody>
</table>
<p>更多异常：</p>
<pre><code><code>ArithmeticError
AssertionError
AttributeError
BaseException
BufferError
BytesWarning
DeprecationWarning
EnvironmentError
EOFError
Exception
FloatingPointError
FutureWarning
GeneratorExit
ImportError
ImportWarning
IndentationError
IndexError
IOError
KeyboardInterrupt
KeyError
LookupError
MemoryError
NameError
NotImplementedError
OSError
OverflowError
PendingDeprecationWarning
ReferenceError
RuntimeError
RuntimeWarning
StandardError
StopIteration
SyntaxError
SyntaxWarning
SystemError
SystemExit
TabError
TypeError
UnboundLocalError
UnicodeDecodeError
UnicodeEncodeError
UnicodeError
UnicodeTranslateError
UnicodeWarning
UserWarning
ValueError
Warning
ZeroDivisionError</code></pre>
<h3 id="异常处理-1">（4）异常处理：</h3>
<p>​ 检测到异常后“跳”过异常及异常下的代码，保证程序不会被中断</p>
<h4 id="异常处理方法">异常处理方法：</h4>
<h5 id="if-异常处理的方式-----if-处理一些简单的异常">&lt;1&gt; if 异常处理的方式 --- if 处理一些简单的异常</h5>
<pre><code><code>num = input(&quot;&gt;&gt;&quot;)
if num.isdecimal():
    int(num)
if len(num) == 0:
    pass

    # if 处理一些简单的异常,if异常处理的方式</code></pre>
<p>总结：</p>
<p>if判断式的异常处理只能针对某一段代码，对于不同的代码段的相同类型的错误你需要写重复的if来进行处理。</p>
<p>在你的程序中频繁的写与程序本身无关，与异常处理有关的if，会使得你的代码可读性极其的差</p>
<p>if是可以解决异常的，只是存在1,2的问题，所以，千万不要妄下定论 if 不能用来异常处理</p>
<h5 id="try-方式----私人订制">&lt;2&gt; try 方式 -- 私人订制</h5>
<pre><code><code>try:        # 尝试
    int(&quot;alex&quot;)
except ValueError:
    &quot;&quot;&quot;其他代码逻辑&quot;&quot;&quot;</code></pre>
<pre><code><code>try:

    [1,2,3][7]
    print(111)
    dic = {&quot;key&quot;:1}
    dic[&quot;name&quot;]
except Exception:         # 万能异常 -- Exception ， 可以捕获任意异常
    pass</code></pre>
<h3 id="为什么要用异常处理">（5）为什么要用异常处理？</h3>
<h4 id="出现异常异常下方的代码就不执行了出现中断">&lt;1&gt; 出现异常，异常下方的代码就不执行了（出现中断）</h4>
<h4 id="用户体验不良好">&lt;2&gt; 用户体验不良好</h4>
<h3 id="异常分支">（6）异常分支</h3>
<h4 id="根据不同分支执行不同逻辑">&lt;1 &gt; 根据不同分支，执行不同逻辑</h4>
<pre><code><code>try:
    int(input(&quot;请输入数字:&quot;))

except ValueError as e:       # as相当于将报错信息赋值给了e
    print(e)


try:
    int(input(&quot;请输入数字:&quot;))

except Exception as e:
    print(e)

int(input(&quot;请输入数字:&quot;))</code></pre>
<h4 id="分支-万能-else-finally">&lt;2&gt; 分支 + 万能 + else + finally</h4>
<pre><code><code>try:
    num = int(input(&quot;请输入数字:&quot;))
    lst = [1,2,3]
    # dic = {&quot;name&quot;:&quot;mee&quot;,1:&quot;imo&quot;}
    # print(dic[num])
    print(lst[num])

except ValueError as e:
    print(e)

except KeyError as e:
    print(f&quot;没有{e}这个键&quot;)

except IndexError as e:
    print(e)

except Exception as e:
    print(e)

else:
    print(&quot;都没有错,走我!&quot;)

finally:
    print(&quot;有错没有错,都走我!,清理工作&quot;)</code></pre>
<h4 id="try.......except的方式">&lt;3&gt; try.......except的方式</h4>
<pre><code><code>class EvaException(BaseException):
    def __init__(self,msg):
        self.msg = msg
    def __str__(self):
        return self.msg

try:
    a = EvaException(&#39;类型错误&#39;)
    raise a
except EvaException as e:
    print(e)
</code></pre>
<h4 id="使用try..except的方式总结">&lt;4&gt; 使用try..except的方式总结：</h4>
<p>​ 把错误处理和真正的工作分开来</p>
<pre><code><code>代码更易组织，更清晰，复杂的工作任务更容易实现； </code></pre>
<p>​ 毫无疑问，更安全了，不至于由于一些小的疏忽而使程序意外崩溃了；</p>
<h3 id="什么时候使用异常处理">（7）什么时候使用异常处理？</h3>
<p>​ try...except应该尽量少用，因为它本身就是你附加给你的程序的一种异常处理的逻辑，与你的主要的工作是没有关系的这种东西加的多了，会导致你的代码可读性变差，只有在有些异常无法预知的情况下，才应该加上try...except，其他的逻辑错误应该尽量修正</p>
<h2 id="断言">2、断言</h2>
<h4 id="assert-条件">assert 条件</h4>
<pre><code><code>assert 1 == 1

if 1 == 1:
    print(111)

assert 1 == 2
if 1 == 2:
    print(222)
</code></pre>

</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>